org.gradle.jvmargs=-Xmx4G
org.gradle.configureondemand=true
org.gradle.parallel=true

enabledPlatforms=fabric,neoforge

version=0.0.8
group=earth.terrarium.common_storage_lib

minecraftVersion=1.21.1
parchmentVersion=2024.05.01

modMenuVersion=11.0.0
reiVersion=12.0.684

fabricLoaderVersion=0.15.11
fabricApiVersion=0.115.4+1.21.1

neoforgeVersion=21.1.133
